add --with-compat option for makeing compat library

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -471,7 +471,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SONAME_INFO SONAME_VERSION SONAME_MAJOR SONAME_MINOR SONAME_REVISION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S AWK SET_MAKE build build_cpu build_vendor build_os host host_cpu host_vendor host_os ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP EGREP LIBTOOL MAKE PERL RM MKDIR MV DBPATH KR_DEFS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SONAME_INFO SONAME_VERSION SONAME_MAJOR SONAME_MINOR SONAME_REVISION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S AWK SET_MAKE build build_cpu build_vendor build_os host host_cpu host_vendor host_os ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP EGREP LIBTOOL MAKE PERL RM MKDIR MV COMPAT_VERSION DBPATH KR_DEFS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1018,6 +1018,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-pic              try to use only PIC/non-PIC objects default=use both
+  --with-compat=VERSION   build compat library
   --with-sqlite=PATH      sqlite path [default: /usr]
   --with-ipcalc=PATH      prefix of ipcalc library [default: /usr]
   --with-libiconv=PATH    libiconv prefix
@@ -4330,7 +4331,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4333 "configure"' > conftest.$ac_ext
+  echo '#line 4334 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4888,7 +4889,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4891: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4892: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6090,7 +6091,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6093 "configure"' > conftest.$ac_ext
+    echo '#line 6094 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6838,7 +6839,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6841 "configure"
+#line 6842 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6936,7 +6937,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6939 "configure"
+#line 6940 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7665,6 +7666,13 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
+# Check whether --with-compat or --without-compat was given.
+if test "${with_compat+set}" = set; then
+  withval="$with_compat"
+
+fi;
+
+
 # Check whether --with-sqlite or --without-sqlite was given.
 if test "${with_sqlite+set}" = set; then
   withval="$with_sqlite"
@@ -8027,6 +8035,28 @@ _ACEOF
 
   LIBS="-ldl $LIBS"
 
+fi
+
+
+if test "x$with_compat" != "x" && test "$with_compat" != "no" ; then
+	echo "$as_me:$LINENO: checking for compat library version" >&5
+echo $ECHO_N "checking for compat library version... $ECHO_C" >&6
+	if test "$with_compat" = "yes"; then
+		{ { echo "$as_me:$LINENO: error: Don't specify compat library version" >&5
+echo "$as_me: error: Don't specify compat library version" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+
+	compatv=`echo $with_compat | $PERL -pe 's/[0-9]//g'`
+	if test -n "$compatv"; then
+		{ { echo "$as_me:$LINENO: error: compat version is only numeric" >&5
+echo "$as_me: error: compat version is only numeric" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+
+	echo "$as_me:$LINENO: result: $with_compat" >&5
+echo "${ECHO_T}$with_compat" >&6
+	COMPAT_VERSION=$with_compat
 fi
 
 
@@ -10374,6 +10404,7 @@ s,@PERL@,$PERL,;t t
 s,@RM@,$RM,;t t
 s,@MKDIR@,$MKDIR,;t t
 s,@MV@,$MV,;t t
+s,@COMPAT_VERSION@,$COMPAT_VERSION,;t t
 s,@DBPATH@,$DBPATH,;t t
 s,@KR_DEFS@,$KR_DEFS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
