link with libipcalc

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1019,6 +1019,7 @@ Optional Packages:
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-pic              try to use only PIC/non-PIC objects default=use both
   --with-sqlite=PATH      sqlite path [default: /usr]
+  --with-ipcalc=PATH      prefix of ipcalc library [default: /usr]
   --with-libiconv=PATH    libiconv prefix
 
 Some influential environment variables:
@@ -4329,7 +4330,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4332 "configure"' > conftest.$ac_ext
+  echo '#line 4333 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4887,7 +4888,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4890: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4891: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6089,7 +6090,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6092 "configure"' > conftest.$ac_ext
+    echo '#line 6093 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6837,7 +6838,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6840 "configure"
+#line 6841 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6935,7 +6936,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6938 "configure"
+#line 6939 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7671,6 +7672,13 @@ if test "${with_sqlite+set}" = set; then
 fi;
 
 
+# Check whether --with-ipcalc or --without-ipcalc was given.
+if test "${with_ipcalc+set}" = set; then
+  withval="$with_ipcalc"
+
+fi;
+
+
 # Check whether --with-libiconv or --without-libiconv was given.
 if test "${with_libiconv+set}" = set; then
   withval="$with_libiconv"
@@ -8222,9 +8230,128 @@ fi
 	KR_DEFS="$KR_DEFS -DHAVE_LIBSQLITE"
 fi
 
-if test "x$with_libiconv" != "x"; then
+if test "x$with_ipcalc" != "x"; then
+	SEARCHPATH="$dbpath /usr /usr/local /opt"
+
+	for i in $SEARCHPATH
+	do
+		if test -f "$i/lib/libipcalc.so" -o -f "$i/lib/libipcalc.a"; then
+			ipcalclib_tmp="L$i/lib"
+		elif test -f -f "$i/lib64/libipcalc.so" -o -f "$i/lib64/libipcalc.a"; then
+			ipcalclib_tmp="L$i/lib64"
+		fi
+
+		if test "x$ipcalclib_tmp" != "x"; then
+			chk=`echo "$ipcalclib" | sed 's/-//g' | grep "$ipcalclib_tmp "`
+			if test -z "$chk"; then
+				ipcalclib="$ipcalclib -$ipcalclib_tmp "
+			fi
+		fi
+
+		if test -f "$i/include/ipcalc.h"; then
+			ipcalchead_tmp="I$i/include"
+		fi
+
+		if test "x$ipcalchead_tmp" != "x"; then
+			chk=`echo "$ipcalchead" | sed 's/-//g' | grep "$ipcalchead_tmp "`
+			if test -z "$chk" ; then
+				ipcalchead="$ipcalchead -$ipcalchead_tmp "
+			fi
+		fi
+	done
+
+	ipcalclib=`echo "$ipcalclib" | sed 's/^ *\| *$//g'`
+	ipcalchead=`echo "$ipcalchead" | sed 's/^ *\| *$//g'`
+
+	export LDFLAGS="$ipcalclib $LDFALSG"
+	export CPPFLAGS="$ipcalchead $CPPFLAGS"
+fi
+
+
+echo "$as_me:$LINENO: checking for ip2long in -lipcalc" >&5
+echo $ECHO_N "checking for ip2long in -lipcalc... $ECHO_C" >&6
+if test "${ac_cv_lib_ipcalc_ip2long+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lipcalc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char ip2long ();
+int
+main ()
+{
+ip2long ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ipcalc_ip2long=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_ipcalc_ip2long=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ipcalc_ip2long" >&5
+echo "${ECHO_T}$ac_cv_lib_ipcalc_ip2long" >&6
+if test $ac_cv_lib_ipcalc_ip2long = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBIPCALC 1
+_ACEOF
+
+  LIBS="-lipcalc $LIBS"
+
+else
+   { { echo "$as_me:$LINENO: error: Can not find libipcalc library (-lipcalc)" >&5
+echo "$as_me: error: Can not find libipcalc library (-lipcalc)" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+
+if test "x$with_libiconv" != "x" && test "x$with_libiconv" != "xno" ; then
 	if test -f "$with_libiconv/lib/libiconv.so" -o -f "$with_libiconv/lib/libiconv.a"; then
 		export LDFLAGS="$LDFLAGS -L$with_libiconv/lib"
+	elif test -f "$with_libiconv/lib64/libiconv.so" -o -f "$with_libiconv/lib64/libiconv.a"; then
+		export LDFLAGS="$LDFLAGS -L$with_libiconv/lib64"
 	fi
 
 	if test -f "$with_libiconv/include/iconv.h"; then
